### ISSUE TITLE
Postcode issue

### ISSUE THREAD

**Issue by tonytcb** [michaeldrennen/Geonames#11]
Firstly, thank you for this package. It's very good.

I need to use the geoname API to do searches by postcode and suburb, for now, just for Australia. It's possible doit  with the current version of this package?

I ask because I don't see the postcode/placeName in the database. When I found them?

Thanks

**Comment by michaeldrennen** [comment]
You know... I didn't include the postal codes in this library because I didn't need them for the project I built this for.
There is certainly utility there. 
I'll add that on my TODO list.
Thanks.

**Comment by karlshea** [comment]
PR #42 is from my branch with postcode support if you'd like to try it.
