### ISSUE TITLE
Install by country

### ISSUE THREAD

**Issue by tonytcb** [michaeldrennen/Geonames#12]
Hi Michael.

Thanks for the project, again.

I'm facing a problem when I run the install command with a filter by country.
Happens that it's inserting all countries on the database, and just not **Australia**.

I'm using this:
`php artisan geonames:install --country=AU --language=en`

Thanks,

**Comment by michaeldrennen** [comment]
Sorry for the delay.
I've made quite a few changes to the library.
Try again, and let me know if the problem persists.
