### ISSUE TITLE
Nothing to migrate?

### ISSUE THREAD

**Issue by mannverma** [michaeldrennen/Geonames#13]
Hi,
I have followed all the steps to install the package in laravel. But on migration step it is saying "Nothing to migrate.". Please help.

**Comment by amirgee007** [comment]
Testing database connection...
checkDatabase() failed: Make sure you have this line added to your database connection config in the /config/database.php in your project: 'op
tions' => [\PDO::MYSQL_ATTR_LOCAL_INFILE => true,]

as well as i got this....
also no migration

**Comment by michaeldrennen** [comment]
Sorry for the delay.

I have made a lot of changes to the library. Try to run it again, and let me know if you have the same issue.
