### ISSUE TITLE
MyISAM table engine ?

### ISSUE THREAD

**Issue by spout** [michaeldrennen/Geonames#16]
Hello @michaeldrennen ,

Thank you for your great package.
I'm astonished that the table engines are in MyISAM, is there any blocking problem to use InnoDB instead ?

Regards

**Comment by fofo2411** [comment]
I see no problem on using one or the other:

You may want to check this:
https://www.liquidweb.com/kb/mysql-performance-myisam-vs-innodb/

**Comment by spout** [comment]
Closing because not really an issue.
