### ISSUE TITLE
command to add a language ?

### ISSUE THREAD

**Issue by Nuranto** [michaeldrennen/Geonames#19]
How to add a new language without reinstalling all data ?

**Comment by michaeldrennen** [comment]
`
// To add english (en) to your system...
$languageCode = 'en';
$dbConnection = 'testing';
GeoSetting::addLanguage($languageCode, $dbConnection );`

But really the language functionality appears to only be useful for determining which FeatureCodes you want to include in your system.

So really you could just this from the command line:

`php artisan geonames:feature-code --language=en --connection=testing`
