### ISSUE TITLE
Class 'FeatureClassSeeder' not found

### ISSUE THREAD

**Issue by Snake231088** [michaeldrennen/Geonames#2]
After launch php artisan migrate i received this error:
Class 'FeatureClassSeeder' not found

**Comment by nelson6e65** [comment]
This is because `src/Seeders` is not autoloaded.
You can _"fix"_ it by autoloading that dir in your `composer.json`:

```js
// . . .
    "autoload": {
        "classmap": [
            "database",
            "vendor/michaeldrennen/geonames/src/Seeders" // <---- HERE
        ],
        "psr-4": {
            "App\\": "app/"
        }
    }
// . . .
```

**Comment by michaeldrennen** [comment]
Try the newest version. That's been resolved.
