### ISSUE TITLE
Does this work on Laravel 5.8?

### ISSUE THREAD

**Issue by jeraldpunx** [michaeldrennen/Geonames#21]
after I install this, how to use this? there is no tutorial in readme. only install

**Comment by jeraldpunx** [comment]
not working in laravel 5.8

![image](https://user-images.githubusercontent.com/5249781/55955572-5efc0280-5c94-11e9-8745-a6727a980e3b.png)

**Comment by danijar2000** [comment]
Add 
"require": {
     "nesbot/carbon": "2.16.3 as 1.34.0"
}
in composer.json

**Comment by michaeldrennen** [comment]
The objective is to have this work with Laravel 5.8.
The Carbon library in the composer file has been updated.
