### ISSUE TITLE
laravel geonames:install 

### ISSUE THREAD

**Issue by ultrasibz** [michaeldrennen/Geonames#22]
When i try and install i get

The database connection name was set to: mysql
Testing database connection...
Undefined offset: 1001

**Comment by muhammad-tanveerullah** [comment]
Facing the same issue when installing. Can someone please help us with this?

php artisan geonames:install --country=US --language=en

The database connection name was set to: mysql
Testing database connection...
Undefined offset: 1001

**Comment by AndreyKimKemerovo** [comment]
Was facing same issue, fixed by changing config/database.php:
`'options' => extension_loaded('pdo_mysql') ? array_filter([
                PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA')
            ]) : [],`
to
`'options' => extension_loaded('pdo_mysql') ? array_filter([
                PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
                PDO::MYSQL_ATTR_LOCAL_INFILE => true
            ]) : [],`

**Comment by skywalkerAlex** [comment]
In the database.php config file, Put this code "PDO::MYSQL_ATTR_LOCAL_INFILE => true,"
like the below:
'mysql' => [
            'options' => extension_loaded('pdo_mysql') ? array_filter([
                PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
                PDO::MYSQL_ATTR_LOCAL_INFILE => true,
            ]) : [],
        ],

**Comment by michaeldrennen** [comment]
Change made in most recent commit.
