### ISSUE TITLE
Missing indexes

### ISSUE THREAD

**Issue by Nuranto** [michaeldrennen/Geonames#24]
geonames_admin_1_codes - geonameid -> primary
geonames_admin_1_codes - country_code -> index
geonames_admin_1_codes - admin1_code -> index

geonames_admin_2_codes - geonamieid -> primary
geonames_admin_2_codes - country_code -> index
geonames_admin_2_codes - admin1_code -> index
geonames_admin_2_codes - admin2_code -> index
geonames_admin_2_codes - country_code, admin1_code -> index

**Comment by michaeldrennen** [comment]
Thanks @Nuranto 
Yep. Some additions were justified.
The addition of the other indexes should really be left up to the individual developer.
The required indexes could vary quite a bit depending on how you are using the Geonames data.
That being said, the indexes you suggested probably fit most use cases.
Easy enough for me to add them to the package, and let developers delete them from their installation of they see a pressing need to do so.
Your requested changes have been added to the repository.

**Comment by Nuranto** [comment]
Thanks !
