### ISSUE TITLE
Will not install on laravel 6.4

### ISSUE THREAD

**Issue by AlanGreyjoy** [michaeldrennen/Geonames#28]
`Problem 1
    - Conclusion: remove laravel/framework v6.4.0
    - Conclusion: don't install laravel/framework v6.4.0
    - michaeldrennen/geonames v2.0.0 requires illuminate/routing ^5.8 -> satisfiable by laravel/framework[5.8.x-dev], illuminate/routing[5.8.x-dev, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5
.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.4, v5.8.8, v5.8.9].
    - michaeldrennen/geonames v2.0.1 requires illuminate/routing ^5.8 -> satisfiable by laravel/framework[5.8.x-dev], illuminate/routing[5.8.x-dev, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5
.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.4, v5.8.8, v5.8.9].
    - michaeldrennen/geonames v2.0.2 requires laravel/framework ^5.8 -> satisfiable by laravel/framework[5.8.x-dev].
    - michaeldrennen/geonames v2.x-dev requires illuminate/routing ^5.8 -> satisfiable by laravel/framework[5.8.x-dev], illuminate/routing[5.8.x-dev, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27,
v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.4, v5.8.8, v5.8.9].
    - Can only install one of: laravel/framework[5.8.x-dev, v6.4.0].
    - don't install illuminate/routing 5.8.x-dev|don't install laravel/framework v6.4.0
    - don't install illuminate/routing v5.8.0|don't install laravel/framework v6.4.0
    - don't install illuminate/routing v5.8.11|don't install laravel/framework v6.4.0
    - don't install illuminate/routing v5.8.12|don't install laravel/framework v6.4.0
    - don't install illuminate/routing v5.8.14|don't install laravel/framework v6.4.0
    - don't install illuminate/routing v5.8.15|don't install laravel/framework v6.4.0
    - don't install illuminate/routing v5.8.17|don't install laravel/framework v6.4.0
    - don't install illuminate/routing v5.8.18|don't install laravel/framework v6.4.0
    - don't install illuminate/routing v5.8.19|don't install laravel/framework v6.4.0
    - don't install illuminate/routing v5.8.2|don't install laravel/framework v6.4.0
    - don't install illuminate/routing v5.8.20|don't install laravel/framework v6.4.0
    - don't install illuminate/routing v5.8.22|don't install laravel/framework v6.4.0
    - don't install illuminate/routing v5.8.24|don't install laravel/framework v6.4.0
    - don't install illuminate/routing v5.8.27|don't install laravel/framework v6.4.0
    - don't install illuminate/routing v5.8.28|don't install laravel/framework v6.4.0
    - don't install illuminate/routing v5.8.29|don't install laravel/framework v6.4.0
    - don't install illuminate/routing v5.8.3|don't install laravel/framework v6.4.0
    - don't install illuminate/routing v5.8.30|don't install laravel/framework v6.4.0
    - don't install illuminate/routing v5.8.31|don't install laravel/framework v6.4.0
    - don't install illuminate/routing v5.8.32|don't install laravel/framework v6.4.0
    - don't install illuminate/routing v5.8.33|don't install laravel/framework v6.4.0
    - don't install illuminate/routing v5.8.34|don't install laravel/framework v6.4.0
    - don't install illuminate/routing v5.8.35|don't install laravel/framework v6.4.0
    - don't install illuminate/routing v5.8.4|don't install laravel/framework v6.4.0
    - don't install illuminate/routing v5.8.8|don't install laravel/framework v6.4.0
    - don't install illuminate/routing v5.8.9|don't install laravel/framework v6.4.0
    - Installation request for laravel/framework (locked at v6.4.0, required as ^6.2) -> satisfiable by laravel/framework[v6.4.0].
    - Installation request for michaeldrennen/geonames ^2.0 -> satisfiable by michaeldrennen/geonames[v2.0.0, v2.0.1, v2.0.2, v2.x-dev].

Installation failed, reverting ./composer.json to its original content.
`

**Comment by michaeldrennen** [comment]
The newest release works with Laravel v7.
Are you able to upgrade to 7?

**Comment by michaeldrennen** [comment]
Laravel has already moved to version 8. I am not planning on making a version of Geonames for Laravel 6.
