### ISSUE TITLE
Laravel 7 support ?

### ISSUE THREAD

**Issue by Nuranto** [michaeldrennen/Geonames#31]

**Comment by Nuranto** [comment]
@michaeldrennen I saw you committed support for L7, but not released. Is there an issue about it I could help with ?

**Comment by joserick** [comment]
@Nuranto I tried of install you "Fork" and I got same problem, that laravel 6 is necessary, and at the end I had to do another "Fork" change "^6.0|^7.0" for only "^7.0"

P.S. In #33 I see that the "The Travis CI" failed, I don't know if it has something to do with it.

**Comment by Nuranto** [comment]
@joserick Strange, it's working here...?

Yes the test fail on database migrations. I think it is because @michaeldrennen is refactoring this part, but in my case that's not important as the migrations were already processed.

**Comment by michaeldrennen** [comment]
Fixed in new release.
