### ISSUE TITLE
Laravel 7 not supporting 

### ISSUE THREAD

**Issue by skywalkerAlex** [michaeldrennen/Geonames#35]
Hello Michael and thank you for your contribution!
Will be any updates about latest Laravel?

Log file:
  Problem 1
    - Conclusion: remove laravel/framework v7.9.2
    - Conclusion: don't install laravel/framework v7.9.2
    - michaeldrennen/geonames v3.0.0 requires illuminate/database ^6.8 -> satisfiable by laravel/framework[6.x-dev], illuminate/database[6.x-dev, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.18.1, v6.18.10, v6.18.11, v6.18.2, v6.18.3, v6.18.4, v6.18.5, v6.18.6, v6.18.7, v6.18.8, v6.18.9, v6.8.0].
    - michaeldrennen/geonames v3.0.1 requires illuminate/database ^6.8 -> satisfiable by laravel/framework[6.x-dev], illuminate/database[6.x-dev, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.18.1, v6.18.10, v6.18.11, v6.18.2, v6.18.3, v6.18.4, v6.18.5, v6.18.6, v6.18.7, v6.18.8, v6.18.9, v6.8.0].
    - Can only install one of: laravel/framework[6.x-dev, v7.9.2].
    - don't install illuminate/database 6.x-dev|don't install laravel/framework v7.9.2
    - don't install illuminate/database v6.10.0|don't install laravel/framework v7.9.2
    - don't install illuminate/database v6.11.0|don't install laravel/framework v7.9.2
    - don't install illuminate/database v6.12.0|don't install laravel/framework v7.9.2
    - don't install illuminate/database v6.13.0|don't install laravel/framework v7.9.2
    - don't install illuminate/database v6.13.1|don't install laravel/framework v7.9.2
    - don't install illuminate/database v6.14.0|don't install laravel/framework v7.9.2
    - don't install illuminate/database v6.15.0|don't install laravel/framework v7.9.2
    - don't install illuminate/database v6.15.1|don't install laravel/framework v7.9.2
    - don't install illuminate/database v6.16.0|don't install laravel/framework v7.9.2
    - don't install illuminate/database v6.17.0|don't install laravel/framework v7.9.2
    - don't install illuminate/database v6.17.1|don't install laravel/framework v7.9.2
    - don't install illuminate/database v6.18.0|don't install laravel/framework v7.9.2
    - don't install illuminate/database v6.18.1|don't install laravel/framework v7.9.2
    - don't install illuminate/database v6.18.10|don't install laravel/framework v7.9.2
    - don't install illuminate/database v6.18.11|don't install laravel/framework v7.9.2
    - don't install illuminate/database v6.18.2|don't install laravel/framework v7.9.2
    - don't install illuminate/database v6.18.3|don't install laravel/framework v7.9.2
    - don't install illuminate/database v6.18.4|don't install laravel/framework v7.9.2
    - don't install illuminate/database v6.18.5|don't install laravel/framework v7.9.2
    - don't install illuminate/database v6.18.6|don't install laravel/framework v7.9.2
    - don't install illuminate/database v6.18.7|don't install laravel/framework v7.9.2
    - don't install illuminate/database v6.18.8|don't install laravel/framework v7.9.2
    - don't install illuminate/database v6.18.9|don't install laravel/framework v7.9.2
    - don't install illuminate/database v6.8.0|don't install laravel/framework v7.9.2
    - Installation request for laravel/framework (locked at v7.9.2, required as ^7.0) -> satisfiable by laravel/framework[v7.9.2].
    - Installation request for michaeldrennen/geonames ^3.0 -> satisfiable by michaeldrennen/geonames[v3.0.0, v3.0.1].

**Comment by michaeldrennen** [comment]
Fixed in new release.

**Comment by wrabit** [comment]
I'm getting:

**Comment by wrabit** [comment]
How can we install the latest version? I can't seem to install anything other than v3 (which will not install on Laravel v7)

**Comment by skywalkerAlex** [comment]
@michaeldrennen Thank you very much for your contribution!
It works fine now.
