### ISSUE TITLE
PHP requirement mismatch with Laravel

### ISSUE THREAD

**Issue by MLouis** [michaeldrennen/Geonames#41]
Hello !
I tried to install this package with `composer require michaeldrennen/geonames` unfortunately I got a similar message as #28 
So I tried with `composer require michaeldrennen/geonames:^7.0` and got:

>  [InvalidArgumentException]                                                                                         
  Package michaeldrennen/geonames at version ^7.0 has a PHP requirement incompatible with your PHP version (7.2.32)

Laravel 7.x (7.19.1 in my case) has PHP ^7.2.5 required.
Should'n't your package requirement match the Laravel one ?

I've managed to install it with `composer require michaeldrennen/geonames:^7.0 --ignore-platform-reqs` but I'm scared it will mess something up :fearful: 

Thanks for your work :tada:

**Comment by michaeldrennen** [comment]
Agreed. Fixed. Thanks!
