### ISSUE TITLE
Geonames updates - Alternate names ?

### ISSUE THREAD

**Issue by Nuranto** [michaeldrennen/Geonames#45]
It seems there is no update for the table `geonames_alternate_names`, am I right ?
It is quite an important table since this is where the postcode are.

**Comment by Nuranto** [comment]
After some research, it seems my issue is not linked to a lack of update (even if it is still a thing)
I was looking for postal code of "Le Lignon" in Switzerland (which should be 1219). However I cannot find it in file http://download.geonames.org/export/dump/alternatenames/CH.zip even it shows 1219 in https://www.geonames.org/postalcode-search.html?q=Le+Lignon&country=CH

What am I missing here ? Are the data from http://download.geonames.org/export/dump/ not complete or up to date ?

**Comment by karlshea** [comment]
Check out my PR #42, it adds the dedicated postal code table. I checked in my import and '1219' maps to "Le Lignon, Genève, CH"

**Comment by Nuranto** [comment]
Oh, seems perfect ! I wasn't aware of such data, I always thought it was stored in alternate names! Thank you @karlshea! 
@michaeldrennen You think that can be merged on master ?

**Comment by michaeldrennen** [comment]
@karlshea 
Left a question for you in the PR.

**Comment by Nuranto** [comment]
@karlshea @michaeldrennen 
There's an issue with this. I think it lacks of some encoding conversion or something ? 

Example (postal_code = 94430) :

<img width="1426" alt="Capture d’écran 2021-06-19 à 16 18 52" src="https://user-images.githubusercontent.com/1633463/122645299-15cc5680-d11a-11eb-8504-ea9782da44db.png">

**Comment by Nuranto** [comment]
It works if i add `CHARACTER SET UTF8` in the `LOAD DATA LOCAL INFILE` query...
It's strange, i don't have the issue with other geonames tables
