### ISSUE TITLE
PostgreSQL support

### ISSUE THREAD

**Issue by Gnative** [michaeldrennen/Geonames#5]
Current DB queries       

`DB::statement('CREATE TABLE ' . self::TABLE_WORKING . ' LIKE ' . self::TABLE . ';');`

are not supported by PostgreSQL.
Throws error.

**Comment by altaraven** [comment]
Agree, the package is MySQL-dependent. Please add PG support
Even migrations are with MyISAM stuff... and they cannot be overwritten

**Comment by michaeldrennen** [comment]
True story.

Feel free to address this in a Pull Request if you want.

I took a look at this a while back, and it would require some reworking that I didn't have time for.

No plans on revisiting it in the near future, but you're free to.
