### ISSUE TITLE
mmap() failed: [12] Cannot allocate memory

### ISSUE THREAD

**Issue by lareck** [michaeldrennen/Geonames#6]
Running, "php artisan geonames:install" on a homestead installations eventually runs out of memory. PHP memory usage increases until all available memory is consumed. Not sure is this a system configuration issue or an issue with the alternate names command.

Split file #289 of 2583 has 5000 rows.
Inserting alternate names 1359/5000 [▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░░]  27%

mmap() failed: [12] Cannot allocate memory

mmap() failed: [12] Cannot allocate memory
PHP Fatal error:  Out of memory (allocated 4495486976) (tried to allocate 16384 bytes) in /vagrant/dr-services/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 330

mmap() failed: [12] Cannot allocate memory

mmap() failed: [12] Cannot allocate memory
PHP Fatal error:  Out of memory (allocated 4495486976) (tried to allocate 65536 bytes) in /vagrant/dr-services/vendor/laravel/framework/src/Illuminate/Auth/SessionGuard.php on line 18

**Comment by michaeldrennen** [comment]
Looks like the split files are too big for your Homestead set up.

Look inside:
https://github.com/michaeldrennen/Geonames/blob/master/src/Console/AlternateName.php

I set the lines per split file as a constant at the top of that file.

Run a test on your Homestead install where you manually edit that const value before you run the install command.

Lower it to 1000 for starters.

If that solves your problem, then I can add lines per split file as an option for the install command.

**Comment by tpelham42** [comment]
I was experiencing a similar issue using WampServer during the alternate names import. The culprit was "DB::enableQueryLog();" on line 389 of the AlternateNames.php file mentioned above. The query logging was generating memory for each record created until it reached critical failure. Commenting out/removing line 389 fixed the issue.

**Comment by michaeldrennen** [comment]
@tpelham42 Bingo. I'll remove that in the next release.
