### ISSUE TITLE
checkDatabase() failed

### ISSUE THREAD

**Issue by markxxv** [michaeldrennen/Geonames#7]
I had a strange error:

First I installed the package, then i had run migrations, so migration succeeded, a have all tables in my DB, but when i run `php artisan geonames:install` this error occurs:

`checkDatabase() failed: Make sure you have this line added to your database connection config in the /config/database.php in your project: 'options' => [\PDO::MYSQL_ATTR_LOCAL_INFILE => true,]`

Thnx for any idea!

**Comment by uniwertz** [comment]
Add an 'options' array in config/database.php:
connections.mysql.options = [\PDO::MYSQL_ATTR_LOCAL_INFILE => true]

**Comment by michaeldrennen** [comment]
@uniwertz has it. 
Thoughts on how I could re-word that error message to make it more clear?
